#@TYPE: Machine
#@NAME: OSD62-PM-BRK (R5F)
#@DESCRIPTION: Machine configuration for OSD62-PM-BRK (R5F core)

require conf/machine/include/k3r5.inc

SYSFW_SOC = "am62x"
SYSFW_CONFIG = "osd62x"
SYSFW_SUFFIX = "hs-fs"

UBOOT_MACHINE = "am62x_osd62x_r5_defconfig"
